import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import os

# Ensure the output directory exists
os.makedirs("output_plots", exist_ok=True)

# ==========================================
# 1. DATA PIPELINE
# ==========================================
# Loading the tensor data generated by Tempest
file_path = '../pipeline_results/advection_rk4_upwind_advec_gauss_periodic_N5000_dt0.005_dx0.05/spatial_data.npz'
data = np.load(file_path)
raw_matrix = data['ml_tensor_data']  # Shape: (Total_Time_Steps, Grid_Size_N)

# Convert the entire matrix to a PyTorch tensor
tensor_matrix = torch.tensor(raw_matrix, dtype=torch.float32)

# Keep a separate y_train_np for the final plotting comparison
y_train_np = raw_matrix[1:, :] 

# ==========================================
# 2. PHYSICS CONSTRAINTS (PINN)
# ==========================================
def physics_loss_energy_conservation(predicted_state, initial_energy):
    # L2 Norm: We square the values
    predicted_energy = torch.mean(predicted_state**2, dim=1)
    
    # Punish any deviation from the starting energy
    conservation_error = torch.mean((predicted_energy - initial_energy)**2)
    return conservation_error

# ==========================================
# 3. ARCHITECTURE
# ==========================================
class Surrogate(nn.Module):
    def __init__(self, grid_size):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(grid_size, 256),
            nn.ReLU(),  
            nn.Linear(256, 256),
            nn.ReLU(),
            nn.Linear(256, grid_size) 
        )

    def forward(self, x):
        return self.network(x)

grid_size = tensor_matrix.shape[1]
model = Surrogate(grid_size)

# ==========================================
# 4. AUTOREGRESSIVE TRAINING LOOP
# ==========================================
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

# Calculate the true initial ENERGY before training starts (using T=0)
initial_energy = torch.mean(tensor_matrix[0]**2) 

epochs = 500
lambda_physics = 0.1  
unroll_steps = 5  # Train the model to survive its own errors 5 steps into the future

print(f"Starting Autoregressive Training (Unrolling {unroll_steps} steps)...")

for epoch in range(epochs):
    optimizer.zero_grad()
    
    # Start with all valid inputs
    current_predictions = tensor_matrix[:-unroll_steps, :] 
    
    total_data_loss = 0
    total_physics_loss = 0
    
    # Push the model 'unroll_steps' into the future
    for step in range(1, unroll_steps + 1):
        # Predict the next step using the model's OWN previous output
        current_predictions = model(current_predictions)
        
        # Grab the true target for this specific future step
        target_states = tensor_matrix[step : len(tensor_matrix) - unroll_steps + step, :]
        
        # Accumulate the errors
        total_data_loss += loss_fn(current_predictions, target_states)
        total_physics_loss += physics_loss_energy_conservation(current_predictions, initial_energy)

    # Average the accumulated losses over the unroll sequence
    avg_data_loss = total_data_loss / unroll_steps
    avg_physics_loss = total_physics_loss / unroll_steps
    
    # Combine and Backpropagate through time
    final_loss = avg_data_loss + (lambda_physics * avg_physics_loss)
    final_loss.backward()
    optimizer.step()
    
    if epoch % 50 == 0:
        print(f"Epoch {epoch:3} | Data Loss: {avg_data_loss.item():.6f} | Physics Loss: {avg_physics_loss.item():.6f}")

# ==========================================
# 5. AUTOREGRESSIVE ROLLOUT & VISUALIZATION
# ==========================================
model.eval()

rollout_steps = 500 
current_state = tensor_matrix[0].unsqueeze(0) 

ml_history = [current_state.squeeze().detach().numpy()]

print(f"\nStarting {rollout_steps}-step autoregressive rollout test...")

with torch.no_grad():
    for step in range(rollout_steps):
        next_state = model(current_state)
        ml_history.append(next_state.squeeze().detach().numpy())
        current_state = next_state

print("Generating visualization...")

step_to_plot = rollout_steps 
ml_final_state = ml_history[step_to_plot]

plt.figure(figsize=(10, 5))
plt.title(f"Autoregressive Rollout: T={step_to_plot} (Dense Network + L2 + Unrolled Training)")

# Safe Plotting: Only plot True Physics if we have enough ground truth data
if (step_to_plot - 1) < len(y_train_np):
    true_final_state = y_train_np[step_to_plot - 1] 
    plt.plot(true_final_state, label=f"True Physics (T={step_to_plot})", color="blue", alpha=0.6, linewidth=2)
else:
    print(f"Warning: Outran ground truth data (Max T={len(y_train_np)}). Plotting ML prediction only.")

# Plot the ML's compounded guess
plt.plot(ml_final_state, label=f"ML Rollout (T={step_to_plot})", linestyle="--", color="red", linewidth=2)

plt.legend()
plt.grid(True)

plot_filename = f"output_plots/unrolled_L2_rollout_T{step_to_plot}.png"
plt.savefig(plot_filename, bbox_inches='tight')
print(f"Saved highly constrained rollout plot as '{plot_filename}'")